project_name: prjkt

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
  - title: Features
    regexp: "^.*(✨|⚡️)[(\\w)]*.*$"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*(🐛|🚑)[(\\w)]*.*$"
    order: 1
  - title: Others
    order: 999
  filters:
    exclude:
      - '^(📝|✅|👷|🚨|🚧|🔀|🔖|⏪|✏️)'

release:
  github:
    owner: patheticGeek
    name: prjkt
